# Regex or list to select feature columns
# (Cell profiler columns start with an uppercase and contain an underscore)
feature_cols: "^[A-Z][A-Za-z0-9]*_.*"

# SQL like WHERE clause to select control samples, where the query will be of
# the form "SELECT * FROM self WHERE {control_sample_query}".
control_sample_query: "variantClass = 'WT'"

# The name of the column containing the batch
batch_col_name: "tile_experiment_well"

# Column containing biological labels
label_col_name: "aaChanges"
